#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# MalO gateway responder forensics.
#
# Answers one question: when the Android app shows «Шлюз вернул ошибку NNN»,
# WHO produced that status — the MalO Express app, or an intermediary (Railway
# edge / Cloudflare) that the request never got past?
#
# The MalO gateway always answers with JSON shaped like
#   {"ok":false,"error":{"code":"...","message":"..."}}
# and `server/src` contains no rate limiter at all, so a 429 carrying anything
# other than that JSON was NOT generated by this codebase.
#
#   ./server/scripts/diagnose-gateway.sh
#   ./server/scripts/diagnose-gateway.sh --url https://malo.up.railway.app --key "$MALO_CLIENT_KEY"
#   ./server/scripts/diagnose-gateway.sh --invoice      # also replay the real POST
# ---------------------------------------------------------------------------
set -u

URL="${MALO_PUBLIC_URL:-${MALO_GATEWAY_URL:-https://malo.up.railway.app}}"
KEY="${MALO_CLIENT_KEY:-}"
DO_INVOICE=0
ASSET="USDT"

while [ $# -gt 0 ]; do
  case "$1" in
    --url) URL="${2:-}"; shift 2 ;;
    --key) KEY="${2:-}"; shift 2 ;;
    --asset) ASSET="${2:-USDT}"; shift 2 ;;
    --invoice) DO_INVOICE=1; shift ;;
    -h|--help) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

URL="${URL%/}"
command -v curl >/dev/null 2>&1 || { echo "curl is required" >&2; exit 1; }

if [ -t 1 ]; then B=$'\033[1m'; R=$'\033[31m'; G=$'\033[32m'; Y=$'\033[33m'; C=$'\033[36m'; N=$'\033[0m'
else B=""; R=""; G=""; Y=""; C=""; N=""; fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

hdr() { # hdr <file> <name>  -> value of the LAST occurrence, trimmed
  tr -d '\r' < "$1" | grep -i "^$2:" | tail -1 | cut -d: -f2- | sed 's/^[[:space:]]*//'
}

# Did the MalO Express app itself write this body?
is_malo_body() {
  grep -qE '"service"[[:space:]]*:[[:space:]]*"malo-payment-gateway"' "$1" && return 0
  grep -qE '"ok"[[:space:]]*:[[:space:]]*(true|false)' "$1" && \
  grep -qE '("error"[[:space:]]*:[[:space:]]*\{|"invoice"|"plan"|"paymentMethods"|"subscription"|"cryptobot")' "$1" && return 0
  return 1
}

VERDICTS="$TMP/verdicts"; : > "$VERDICTS"

probe() { # probe <label> <method> <path> [data]
  local label="$1" method="$2" path="$3" data="${4:-}"
  local H="$TMP/h.$$" BODY="$TMP/b.$$" code

  set -- -sS -o "$BODY" -D "$H" -w '%{http_code}' --max-time 25 -X "$method" \
         -H 'Accept: application/json' -H 'User-Agent: MalO-diagnose/1.0'
  [ -n "$KEY" ] && set -- "$@" -H "X-MalO-Client-Key: $KEY"
  [ -n "$data" ] && set -- "$@" -H 'Content-Type: application/json' --data "$data"

  printf '%s\n' "${B}── ${label}${N}  ${C}${method} ${URL}${path}${N}"
  if ! code="$(curl "$@" "${URL}${path}" 2>"$TMP/err")"; then
    printf '   %sTRANSPORT FAILURE%s %s\n\n' "$R" "$N" "$(tr -d '\n' < "$TMP/err")"
    echo "transport" >> "$VERDICTS"
    return
  fi

  local server cfray retry rlimit via
  server="$(hdr "$H" server)";      cfray="$(hdr "$H" cf-ray)"
  retry="$(hdr "$H" retry-after)";  via="$(hdr "$H" via)"
  rlimit="$(tr -d '\r' < "$H" | grep -iE '^(x-)?ratelimit[^:]*:' | sed 's/^/      /')"

  local colour="$G"
  [ "$code" -ge 400 ] 2>/dev/null && colour="$Y"
  [ "$code" -ge 500 ] 2>/dev/null && colour="$R"
  [ "$code" = "429" ] && colour="$R"

  printf '   status      %s%s%s\n' "$colour" "$code" "$N"
  [ -n "$server" ] && printf '   server      %s\n' "$server"
  [ -n "$cfray"  ] && printf '   cf-ray      %s  %s(Cloudflare in front)%s\n' "$cfray" "$Y" "$N"
  [ -n "$via"    ] && printf '   via         %s\n' "$via"
  [ -n "$retry"  ] && printf '   retry-after %s%s s%s\n' "$Y" "$retry" "$N"
  [ -n "$rlimit" ] && printf '%s\n' "$rlimit"

  if is_malo_body "$BODY"; then
    printf '   body        %sMalO gateway JSON%s — the Express app answered\n' "$G" "$N"
    local ecode
    ecode="$(sed -n 's/.*"code"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$BODY" | head -1)"
    [ -n "$ecode" ] && printf '   error.code  %s%s%s\n' "$Y" "$ecode" "$N"
    head -c 300 "$BODY" | sed 's/^/      /'; echo
    echo "origin:$code" >> "$VERDICTS"
  else
    printf '   body        %sNOT MalO JSON%s — answered before reaching the app\n' "$R" "$N"
    head -c 300 "$BODY" | tr -d '\r' | sed 's/^/      /'; echo
    if [ -n "$cfray" ] || grep -qi 'cloudflare\|error code: 1015' "$BODY"; then
      echo "cloudflare:$code" >> "$VERDICTS"
    elif printf '%s' "$server" | grep -qi 'railway'; then
      echo "railway-edge:$code" >> "$VERDICTS"
    else
      echo "intermediary:$code" >> "$VERDICTS"
    fi
  fi
  echo
}

printf '\n%sMalO gateway diagnostics%s  target=%s  client-key=%s\n\n' \
  "$B" "$N" "$URL" "$([ -n "$KEY" ] && echo "sent (${#KEY} chars)" || echo "${Y}NOT SET${N}")"

probe "health   (no auth, no side effects)" GET  /api/health
probe "catalog  (auth required)"            GET  /api/catalog
probe "webhooks (prints registered URLs)"   GET  /api/webhooks

if [ "$DO_INVOICE" -eq 1 ]; then
  probe "createInvoice (REAL — replays the failing call)" POST /api/crypto/invoices \
    "{\"userId\":\"malo-diagnose-000001\",\"asset\":\"${ASSET}\"}"
else
  printf '%s(skipping the createInvoice replay — add --invoice to run it)%s\n\n' "$C" "$N"
fi

# ------------------------------------------------------------------ verdict --
printf '%s══ Verdict ══%s\n' "$B" "$N"

if grep -q '^cloudflare:429' "$VERDICTS"; then
  printf '%sCloudflare rate-limited the request (error 1015).%s\n' "$R" "$N"
  echo 'The request never reached your Node process. Check the Cloudflare rules'
  echo 'on the custom domain, or the shared/CGNAT IP your phone exits through.'
elif grep -q '^railway-edge:429' "$VERDICTS"; then
  printf '%sRailway'"'"'s edge proxy returned 429 — not your code.%s\n' "$R" "$N"
  echo 'server/src has no rate limiter, so this was produced before Express.'
  echo 'Nothing will appear in the Railway deploy logs for this request.'
  echo 'Check: account/plan limits in the Railway dashboard, and whether the'
  echo 'client IP is shared (mobile CGNAT, VPN, office NAT).'
elif grep -q '^intermediary:429' "$VERDICTS"; then
  printf '%sAn intermediary returned 429 (body is not MalO JSON).%s\n' "$R" "$N"
  echo 'Inspect the server/via headers printed above to identify the hop.'
elif grep -q '^origin:429' "$VERDICTS"; then
  printf '%sThe Express app returned 429 — unexpected for this codebase.%s\n' "$R" "$N"
  echo 'Something was added in front of createApp(); grep for a rate limiter.'
elif grep -q '^transport' "$VERDICTS"; then
  printf '%sCould not establish a connection.%s DNS/TLS/egress problem, not a 429.\n' "$R" "$N"
elif grep -q '^origin:' "$VERDICTS"; then
  printf '%sThe gateway is reachable and answering with its own JSON.%s\n' "$G" "$N"
  echo 'No 429 reproduced from this network. If the phone still sees 429, the'
  echo 'limit is tied to the phone'"'"'s egress IP, not to the deployment.'
else
  printf '%sInconclusive — see the probes above.%s\n' "$Y" "$N"
fi
echo
